#!/usr/bin/env zsh

echo ''
echo 'Stowing Configs'

cd $HOME/.dotfiles

stow aws --no-folding --adopt
stow conda --no-folding --adopt
stow git --no-folding --adopt
stow java --no-folding --adopt
stow neofetch --no-folding --adopt
stow neovim --no-folding --adopt
stow scripts --no-folding --adopt
stow sdkman --no-folding --adopt
stow ssh --no-folding --adopt
stow tmux --no-folding --adopt
stow zsh --no-folding --adopt
stow fleet --no-folding --adopt
