#!/usr/bin/env zsh

dir=(
    conda
    git
    java
    neofetch
    neovim
    scripts
    sdkman
    ssh
    starship
    zsh
    fleet
    alacritty
    lf
)

stow ${dir[@]} --no-folding --adopt

