#!/usr/bin/env zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

function log() {
    level=$1
    message=$2
    if [[ $level = 'info' ]]; then
        echo -e "${GREEN}$message${NOCOLOR}"
    elif [[ $level = 'warning' ]]; then
        echo -e "${YELLOW}$message${NOCOLOR}"
    else
        echo -e "${RED}$message${NOCOLOR}"
    fi
}



if [ ! -d "$HOME/.dotfiles" ]; then
    log info 'Dotfiles does not exist. Cloning...'
    git clone git@github.com:andriuslima/.dotfiles.git
fi

log info 'Linking configuration'
zsh $HOME/.dotfiles/update

log info 'Running installation script'
zsh $HOME/.bin/install
