#!/usr/bin/env zsh

dir=(
    alacritty
    conda
    fleet
    git
    java
    lf
    neofetch
    neovim
    scripts
    sdkman
    ssh
    starship
    tmux
    zsh
)

stow ${dir[@]} --no-folding --restow
