#!/usr/bin/env zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

function log() {
    level=$1
    message=$2
    if [[ $level = 'info' ]]; then
        echo -e "${GREEN}$message${NOCOLOR}"
    elif [[ $level = 'warning' ]]; then
        echo -e "${YELLOW}$message${NOCOLOR}"
    else
        echo -e "${RED}$message${NOCOLOR}"
    fi
}

log info '|||> Installing Google Cloud'

if [ ! -d "$HOME/.local/google-cloud-sdk" ]; then

  cd $HOME/.local/
  wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-370.0.0-darwin-arm.tar.gz
  tar -xf google-cloud-sdk-370.0.0-darwin-arm.tar.gz
  ./google-cloud-sdk/install.sh --command-completion false --quiet
  ./google-cloud-sdk/bin/gcloud components update
  rm -rf google-cloud-sdk-370.0.0-darwin-arm.tar.gz

else
  log info 'gcloud already installed!'
fi

