#!/usr/bin/env zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

function log() {
    level=$1
    message=$2
    if [[ $level = 'info' ]]; then
        echo -e "${GREEN}$message${NOCOLOR}"
    elif [[ $level = 'warning' ]]; then
        echo -e "${YELLOW}$message${NOCOLOR}"
    else
        echo -e "${RED}$message${NOCOLOR}"
    fi
}


log info '|||> Installing AWS Command Line Interface'

which -s aws
if [[ $? != 0 ]] ; then
  curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
  sudo installer -pkg AWSCLIV2.pkg -target /
  rm AWSCLIV2.pkg
else
    log warning 'AWS CLI already installed'
fi

mkdir $HOME/.aws
ln -s $HOME/Documents/Configuration/AWS/credentials $HOME/.aws/credentials
ln -s $HOME/Documents/Configuration/AWS/config $HOME/.aws/config
