#!/usr/bin/env zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

function log() {
    level=$1
    message=$2
    if [[ $level = 'info' ]]; then
        echo -e "${GREEN}$message${NOCOLOR}"
    elif [[ $level = 'warning' ]]; then
        echo -e "${YELLOW}$message${NOCOLOR}"
    else
        echo -e "${RED}$message${NOCOLOR}"
    fi
}

log info '|||> Setting packages'

packages=(
  mas
  git
  go
  maven
  neofetch
  openssl
  ruby
  rust
  python
  neovim
  yarn
  zsh
  aws-sam-cli
  wget
  fzf
  fd
  ripgrep
  coreutils
  exa
  stow
  jesseduffield/lazygit/lazygit
  lua
  lua-language-server
  stylua
  libevent
  ncurses
  tmux
  bat
  lf
  zoxide
)

casks=(
  jetbrains-toolbox
  postman
  docker
  miniconda
)

mas=(
  975937182   # Fantastical           (3.7.21)
  409183694   # Keynote               (13.1)
  462058435   # Microsoft Excel       (16.76)
  803453959   # Slack                 (4.34.115)
  409201541   # Pages                 (13.1)
  1147396723  # WhatsApp              (2.2335.9)
  462054704   # Microsoft Word        (16.76.1)
  1352778147  # Bitwarden             (2023.8.3)
  409203825   # Numbers               (13.1)
  462062816   # Microsoft PowerPoint  (16.76.1)
)

brew tap mongodb/brew
brew tap aws/tap

brew install --quiet ${packages[@]}
brew install --quiet --cask ${casks[@]}
mas install ${mas[@]}
