#!/usr/bin/env zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

function log() {
    level=$1
    message=$2
    if [[ $level = 'info' ]]; then
        echo -e "${GREEN}$message${NOCOLOR}"
    elif [[ $level = 'warning' ]]; then
        echo -e "${YELLOW}$message${NOCOLOR}"
    else
        echo -e "${RED}$message${NOCOLOR}"
    fi
}

log info '|||> Installing packages'

packages=(
    aws-sam-cli
    bat
    bun
    eza
    fzf
    git
    mas
    maven
    neovim
    openssl
    python@3.12
    stow
    starship
    wget
    yarn
    zsh
)

casks=(
  jetbrains-toolbox
  postman
  docker
  miniconda
  visual-studio-code
  logitune # Manual installer necessary
)

mas=(
    408981434   # iMovie                (10.4.1)
    462058435   # Microsoft Excel       (16.87)
    409201541   # Pages                 (14.1)
    310633997   # ‎WhatsApp             (24.14.85)
    409183694   # Keynote               (14.1)
    462062816   # Microsoft PowerPoint  (16.87)
    803453959   # Slack                 (4.39.90)
    462054704   # Microsoft Word        (16.87)
    409203825   # Numbers               (14.1)
)

brew tap aws/tap
brew tap oven-sh/bun

brew install --quiet ${packages[@]}
brew install --quiet --cask ${casks[@]}
mas install ${mas[@]}
