#!/usr/bin/env zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

function log() {
    level=$1
    message=$2
    if [[ $level = 'info' ]]; then
        echo -e "${GREEN}$message${NOCOLOR}"
    elif [[ $level = 'warning' ]]; then
        echo -e "${YELLOW}$message${NOCOLOR}"
    else
        echo -e "${RED}$message${NOCOLOR}"
    fi
}

log info '|||> Installing fonts'

brew tap homebrew/cask-fonts

log info '||||> Installing Jetbrains Mono'
brew install --cask font-jetbrains-mono-nerd-font

log info '||||> Installing Fira Code Nerd Font'
brew install --cask font-fira-code-nerd-font