#!/usr/bin/env zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

function log() {
    level=$1
    message=$2
    if [[ $level = 'info' ]]; then
        echo -e "${GREEN}$message${NOCOLOR}"
    elif [[ $level = 'warning' ]]; then
        echo -e "${YELLOW}$message${NOCOLOR}"
    else
        echo -e "${RED}$message${NOCOLOR}"
    fi
}

log info '|||> Setting packages'

packages=(
    aws-sam-cli
    bat
    coreutils
    exa
    fd
    fzf
    git
    go
    jesseduffield/lazygit/lazygit
    lf
    libevent
    lua
    mas
    maven
    ncurses
    neofetch
    neovim
    openssl
    python@3.12
    dotnet@6
    ripgrep
    ruby
    rust
    stow
    starship
    wget
    yarn
    zoxide
    zsh
)

casks=(
  jetbrains-toolbox
  postman
  docker
  miniconda
  gitkraken
  visual-studio-code
  zed
)

mas=(
    975937182   # Fantastical           (3.8.9)
    409183694   # Keynote               (13.2)
    408981434   # iMovie                (10.4)
    425424353   # The Unarchiver        (4.3.6)
    462058435   # Microsoft Excel       (16.80)
    803453959   # Slack                 (4.35.131)
    409201541   # Pages                 (13.2)
    #1529448980  # Reeder                (5.4)
    310633997   #‎ WhatsApp             (23.25.80)
    462054704   # Microsoft Word        (16.80)
    1352778147  # Bitwarden             (2023.12.0)
    409203825   # Numbers               (13.2)
    462062816   # Microsoft PowerPoint  (16.80)
    1339170533  # CleanMyMac X          (4.14.6)
)

brew tap aws/tap

brew install --quiet ${packages[@]}
brew install --quiet --cask ${casks[@]}
mas install ${mas[@]}
