#!/usr/bin/env zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

function log() {
    level=$1
    message=$2
    if [[ $level = 'info' ]]; then
        echo -e "${GREEN}$message${NOCOLOR}"
    elif [[ $level = 'warning' ]]; then
        echo -e "${YELLOW}$message${NOCOLOR}"
    else
        echo -e "${RED}$message${NOCOLOR}"
    fi
}

log info '|||> Setting Python packages'

conda=(
  boto3
  awscli-local
  pynvim
  pylint
  jedi
)

conda config --add channels conda-forge
conda update -n base -c defaults conda --yes

python3 -m pip install --upgrade setuptools
python3 -m pip install --upgrade pip

conda install --name base ${conda[@]} --yes
