#!/usr/bin/env zsh

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

function log() {
    level=$1
    message=$2
    if [[ $level = 'info' ]]; then
        echo -e "${GREEN}$message${NOCOLOR}"
    elif [[ $level = 'warning' ]]; then
        echo -e "${YELLOW}$message${NOCOLOR}"
    else
        echo -e "${RED}$message${NOCOLOR}"
    fi
    sleep 1
}

log info '|> Installing macOS necessary softwares and updates.'

softwareupdate --all --install --force
softwareupdate --install-rosetta --agree-to-license 

log info '|> Installing Packages...'
zsh $HOME/.bin/scripts/install_homebrew
zsh $HOME/.bin/scripts/install_packages
zsh $HOME/.bin/scripts/install_aws
# zsh $HOME/.bin/scripts/install_gcloud
zsh $HOME/.bin/scripts/install_sdkman
zsh $HOME/.bin/scripts/install_fonts
zsh $HOME/.bin/scripts/install_zshzap --branch release-v1
log info '|> Packages set'

log info '|> Setting Languages'
zsh $HOME/.bin/scripts/setup_java
zsh $HOME/.bin/scripts/setup_gradle
zsh $HOME/.bin/scripts/setup_node
zsh $HOME/.bin/scripts/setup_python
log info '|> Languages set'

log info '|> Setting configs'
zsh $HOME/.bin/scripts/setup_ssh
zsh $HOME/.bin/scripts/setup_fzf
zsh $HOME/.bin/scripts/setup_macos
log info '|> Configs set'

sudo chsh -s $(which zsh)

log warning 'Reloading shell'
source $XDG_CONFIG_HOME/zsh/.zshrc
 
log info '|> Updating Applications...'
brew upgrade --quiet
brew update --quiet
brew upgrade --cask --quiet
mas upgrade
brew autoremove --quiet
brew cleanup -s --prune=all --quiet

log info '|> Setup completed'
